steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gpt-researcher/wald-research-agent:$COMMIT_SHA', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gpt-researcher/wald-research-agent:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'wald-research-agent'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gpt-researcher/wald-research-agent:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gpt-researcher/wald-research-agent:$COMMIT_SHA'